version: "3"
services:
  postgres:
    container_name: jaspe-test-postgres
    image: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prueba_node
    ports:
      - '5432:5432'
    restart: always

  jaspesoft:
    container_name: jaspe-test-node
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '4567:8080'
